FROM rust:1.82-slim-bookworm as builder
WORKDIR /app

COPY Cargo.toml ./
COPY api/Cargo.toml api/
COPY engine/Cargo.toml engine/
COPY lb/Cargo.toml lb/

RUN mkdir -p api/src && echo "fn main() {}" > api/src/main.rs && \
    mkdir -p lb/src && echo "fn main() {}" > lb/src/main.rs && \
    mkdir -p engine/src && echo "pub fn dummy() {}" > engine/src/lib.rs && \
    mkdir -p engine/src/bin && echo "fn main() {}" > engine/src/bin/build_index.rs

RUN RUSTFLAGS="-C target-cpu=haswell -C link-arg=-s" cargo build --release

COPY lb/src ./lb/src
COPY engine/src ./engine/src

RUN touch lb/src/main.rs && touch engine/src/lib.rs && RUSTFLAGS="-C target-cpu=haswell -C link-arg=-s" cargo build --release --bin rust_lb

FROM gcr.io/distroless/cc-debian12:latest
WORKDIR /app
COPY --from=builder /app/target/release/rust_lb ./rust_lb
CMD ["./rust_lb"]
